logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    health:
      show-details: always
  trace:
    http:
      enabled: true        
        
server:
  port: 10000

# dois servidores
# servidor1 (maquina_boa) - peso 8
# servidor2 (maquina_ruim) - peso 2
spring:
  cloud:
    gateway:
      routes:
      - id: servidor_maquina_boa
        uri: http://localhost:8081
        predicates:
        - Weight=servidores, 8
        - Path=/server
      - id: maquina_boa
        uri: http://localhost:8081
        predicates:
        - Weight=servidoresDePedidos, 8
        - Path=/rest/pedido/novo/**
      - id: servidor_maquina_ruim
        uri: http://localhost:8082
        predicates:
        - Path=/server
        - Weight=servidores, 2
      - id: maquina_ruim
        uri: http://localhost:8082
        predicates:
        - Weight=servidoresDePedidos, 2
        - Path=/rest/pedido/novo/**